name: music_app
description: "A new Flutter project."

version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  just_audio: ^0.9.40
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/songs.json
    - assets/itunes_logo.png
